package com.example.mashinki

object DefaultLists {
    private val defaultEngineersList: List<Engineer> = listOf(
        Engineer(
            id = 1,
            name = "Майкл Афтон",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 450,
            hairColor = HairColor.BLACK,
            favoriteTShirt = TShirtColor.PURPLE,
            experience = Experience.VETERAN,
            reliabilityLevel = 92,
            potentialReliabilityLevel = 93,
            professionLevel = 80,
            potentialProfessionLevel = 81,
            profession = Profession.AERODYNAMIC,
        ),
        Engineer(
            id = 2,
            name = "Лёва Пакетик",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 25,
            hairColor = HairColor.FAIR2,
            favoriteTShirt = TShirtColor.BROWN,
            experience = Experience.NO,
            reliabilityLevel = 1,
            potentialReliabilityLevel = 89,
            professionLevel = 2,
            potentialProfessionLevel = 95,
            profession = Profession.MECHANIC,
        ),
        Engineer(
            id = 3,
            name = "Егор Топор",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 280,
            hairColor = HairColor.FAIR1,
            favoriteTShirt = TShirtColor.RED,
            experience = Experience.PRO,
            reliabilityLevel = 70,
            potentialReliabilityLevel = 80,
            professionLevel = 69,
            potentialProfessionLevel = 79,
            profession = Profession.ELECTRONIC,
        ),
        Engineer(
            id = 4,
            name = "Тоха Телега",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 300,
            hairColor = HairColor.BLOND,
            favoriteTShirt = TShirtColor.GREEN,
            experience = Experience.PRO,
            reliabilityLevel = 75,
            potentialReliabilityLevel = 84,
            professionLevel = 73,
            potentialProfessionLevel = 80,
            profession = Profession.ELECTRONIC,
        ),
        Engineer(
            id = 5,
            name = "Витянь Жиган",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 35,
            hairColor = HairColor.FAIR2,
            favoriteTShirt = TShirtColor.BLUE,
            experience = Experience.INTERN,
            reliabilityLevel = 20,
            potentialReliabilityLevel = 66,
            professionLevel = 24,
            potentialProfessionLevel = 67,
            profession = Profession.MECHANIC,
        ),
        Engineer(
            id = 6,
            name = "Савелий Зебра",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 180,
            hairColor = HairColor.BLACK,
            favoriteTShirt = TShirtColor.GRAY,
            experience = Experience.GOOD,
            reliabilityLevel = 55,
            potentialReliabilityLevel = 67,
            professionLevel = 61,
            potentialProfessionLevel = 79,
            profession = Profession.MECHANIC,
        ),
        Engineer(
            id = 7,
            name = "Женя Мозг",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 950,
            hairColor = HairColor.GRAY,
            favoriteTShirt = TShirtColor.BROWN,
            experience = Experience.VETERAN,
            reliabilityLevel = 99,
            potentialReliabilityLevel = 99,
            professionLevel = 99,
            potentialProfessionLevel = 99,
            profession = Profession.ELECTRONIC,
        ),
        Engineer(
            id = 8,
            name = "Гога Мрачный",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 210,
            hairColor = HairColor.BLOND,
            favoriteTShirt = TShirtColor.RED,
            experience = Experience.GOOD,
            reliabilityLevel = 67,
            potentialReliabilityLevel = 80,
            professionLevel = 52,
            potentialProfessionLevel = 77,
            profession = Profession.AERODYNAMIC,
        ),
        Engineer(
            id = 9,
            name = "Даня Бородач",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 340,
            hairColor = HairColor.BLACK,
            favoriteTShirt = TShirtColor.BLUE,
            experience = Experience.PRO,
            reliabilityLevel = 76,
            potentialReliabilityLevel = 92,
            professionLevel = 77,
            potentialProfessionLevel = 88,
            profession = Profession.ELECTRONIC,
        ),
        Engineer(
            id = 9,
            name = "Миша Сапог",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 80,
            hairColor = HairColor.FAIR1,
            favoriteTShirt = TShirtColor.GREEN,
            experience = Experience.INTERN,
            reliabilityLevel = 40,
            potentialReliabilityLevel = 80,
            professionLevel = 37,
            potentialProfessionLevel = 75,
            profession = Profession.ELECTRONIC,
        ),
        Engineer(
            id = 10,
            name = "Денис Табурет",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 70,
            hairColor = HairColor.FAIR2,
            favoriteTShirt = TShirtColor.GRAY,
            experience = Experience.INTERN,
            reliabilityLevel = 39,
            potentialReliabilityLevel = 82,
            professionLevel = 31,
            potentialProfessionLevel = 78,
            profession = Profession.AERODYNAMIC,
        ),
        Engineer(
            id = 11,
            name = "Толян Качок",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 260,
            hairColor = HairColor.FAIR1,
            favoriteTShirt = TShirtColor.PURPLE,
            experience = Experience.PRO,
            reliabilityLevel = 70,
            potentialReliabilityLevel = 80,
            professionLevel = 71,
            potentialProfessionLevel = 72,
            profession = Profession.AERODYNAMIC,
        ),
        Engineer(
            id = 12,
            name = "Толя Сладкий",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 320,
            hairColor = HairColor.BLACK,
            favoriteTShirt = TShirtColor.GREEN,
            experience = Experience.PRO,
            reliabilityLevel = 80,
            potentialReliabilityLevel = 90,
            professionLevel = 80,
            potentialProfessionLevel = 90,
            profession = Profession.MECHANIC,
        ),
        Engineer(
            id = 13,
            name = "Виталя Вупсен",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 350,
            hairColor = HairColor.GRAY,
            favoriteTShirt = TShirtColor.GRAY,
            experience = Experience.VETERAN,
            reliabilityLevel = 81,
            potentialReliabilityLevel = 82,
            professionLevel = 77,
            potentialProfessionLevel = 77,
            profession = Profession.MECHANIC,
        ),
        Engineer(
            id = 14,
            name = "Сеня Огрызок",
            owner = Team.NONE,
            psychicLevel = 50,
            price = 95,
            hairColor = HairColor.FAIR1,
            favoriteTShirt = TShirtColor.BLUE,
            experience = Experience.GOOD,
            reliabilityLevel = 40,
            potentialReliabilityLevel = 65,
            professionLevel = 44,
            potentialProfessionLevel = 70,
            profession = Profession.ELECTRONIC,
        )
    )

    fun getDefaultEngineersList() = defaultEngineersList
}